apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    chart: podinfo
    targetRevision: 6.0.0
    helm:
      values: |
        replicaCount: 1
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: podinfo-helm.193.146.210.202.nip.io
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: podinfo-helm-tls
              hosts:
                - podinfo-helm.193.146.210.202.nip.io
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
